### ISSUE TITLE
Stop working on Angular 8 after upgrade from 4.11.3 to 4.12.2 when Prod release

### ISSUE THREAD

**Issue by ludufre** [ShankyTiwari/ng-material-multilevel-menu#111]
Hi,

After upgrade from 4.11.3 to 4.12.2 on Angular 8 project with Ionic I receive error when running the project with `production flag`.

Minimal repository with example:

**Working with 4.11.3:**
https://github.com/ludufre/multilevel-angular8-error
```bash
ionic repair
ionic cordova run browser --prod --release
```

**Not working with 4.12.2:**
```bash
npm i ng-material-multilevel-menu@4.12
ionic cordova run browser --prod --release
```
Error:
![image](https://user-images.githubusercontent.com/4112077/80631621-61aad080-8a2c-11ea-9cd3-094cac3d7010.png)

If run without `--prod --release` flag, works great.

I'm not an expert, but I think version 4.12 dropped support to Angular 8, am I right?

**Comment by ShankyTiwari** [comment]
Hi @ludufre Can you share the full error log?

**Comment by ludufre** [comment]
This is everything that appears on the Chrome Console:

```
cordova.29dc09fa9fc3a7aeb58c.js:1 Could not find cordova.js script tag. Plugin loading may fail.
main-es2015.3852369d159b3d16c80f.js:1 ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(s)[a -> e]: 
  StaticInjectorError(Platform: core)[a -> e]: 
    NullInjectorError: No provider for e!
NullInjectorError: StaticInjectorError(s)[a -> e]: 
  StaticInjectorError(Platform: core)[a -> e]: 
    NullInjectorError: No provider for e!
    at M.get (main-es2015.3852369d159b3d16c80f.js:1)
    at main-es2015.3852369d159b3d16c80f.js:1
    at e (main-es2015.3852369d159b3d16c80f.js:1)
    at Ut.get (main-es2015.3852369d159b3d16c80f.js:1)
    at main-es2015.3852369d159b3d16c80f.js:1
    at e (main-es2015.3852369d159b3d16c80f.js:1)
    at Ut.get (main-es2015.3852369d159b3d16c80f.js:1)
    at qr (main-es2015.3852369d159b3d16c80f.js:1)
    at ds.get (main-es2015.3852369d159b3d16c80f.js:1)
    at qr (main-es2015.3852369d159b3d16c80f.js:1)
    at v (polyfills-es2015.c1f142d23713235da53a.js:1)
    at v (polyfills-es2015.c1f142d23713235da53a.js:1)
    at polyfills-es2015.c1f142d23713235da53a.js:1
    at a.invokeTask (polyfills-es2015.c1f142d23713235da53a.js:1)
    at Object.onInvokeTask (main-es2015.3852369d159b3d16c80f.js:1)
    at a.invokeTask (polyfills-es2015.c1f142d23713235da53a.js:1)
    at s.runTask (polyfills-es2015.c1f142d23713235da53a.js:1)
    at _ (polyfills-es2015.c1f142d23713235da53a.js:1)
Le @ main-es2015.3852369d159b3d16c80f.js:1
cordova.29dc09fa9fc3a7aeb58c.js:1 adding proxy for StatusBar
cordova.29dc09fa9fc3a7aeb58c.js:1 adding proxy for Device
cordova.29dc09fa9fc3a7aeb58c.js:1 adding proxy for SplashScreen
StatusBarProxy.js:23 StatusBar is not supported
main-es2015.3852369d159b3d16c80f.js:1 Ionic Native: deviceready event fired after 343 ms
StatusBarProxy.js:23 StatusBar is not supported
screen:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by ShankyTiwari** [comment]
Hi @ludufre from the last couple of days, I am trying to understand this issue and I know It's related to Angular services with V9 according to [this](https://github.com/angular/angular/issues/35759).

```
NullInjectorError: StaticInjectorError(s)[a -> e]: 
StaticInjectorError(Platform: core)[a -> e]: 
NullInjectorError: No provider for e!
```
In the above error, I am not able to understand what is `a` and `e`? Can you please share the less minified error, please?

Till then, I would suggest you use version [4.11.3](https://www.npmjs.com/package/ng-material-multilevel-menu/v/4.11.3).

Thanks

**Comment by ludufre** [comment]
I gave up and ended up updating the whole project to Angular 9. Now working without problems.

**Comment by ShankyTiwari** [comment]
That's great.
